version: "3"

services:
  app:
    build: .
    container_name: portifolio
    environment:
      - VIRTUAL_HOST=portifolio.kuuhaku.dev
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
